apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: nginx:latest 
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
  restartPolicy: Never
