apiVersion: v1
kind: Pod
metadata:
  name: nginx3-pod
  namespace: ns2
spec:
  containers:
  - name: test-container
    image: nginx 
    command: ["/bin/bash", "-c", "while true; do curl http://nginx.ns1:80; sleep 5; done"]
  restartPolicy: Never
