apiVersion: v1
kind: Service
metadata:
  namespace: ns1
  name: my-nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 80
