apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do date >> /date/date.html; sleep 1; done"]
        volumeMounts:
        - name: nginx-vol
          mountPath: /date
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 20m"]
      volumes:
      - name: nginx-vol
        emptyDir: {}
