apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-volume
      mountPath: /etc/cfg
  volumes:
  - name: nginx-volume
    configMap:
      name: cfgvolume
  restartPolicy: Always
