apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/liveness
    args:
    - /server
    ports:
    - name: liveness-port
      containerPort: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
    startupProbe:
      httpGet:
        path: /healthz
        port: liveness-port
    failureThreshold: 30
    periodSeconds: 10
