apiVersion: v1
kind: Pod
metadata:
  name: goproxy-2
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
      name: liveness-port
    livenessProbe:
      tcpSocket:
        port: liveness-port
      initialDelaySeconds: 15
      periodSeconds: 20
