apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 10; while true; do date > /usr/share/nginx/html/date.html; sleep 1; done; sleep 1200"]
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-data
          emptyDir: {}
