---
- name: Playbook to Install Packages
  hosts:
    - local
  tasks:
  - name: Go in this directory
    ansible.builtin.command: chdir=/root/work/lesson03 touch txt.txt
  - name: apply
    ansible.builtin.command: chdir=~/work/lesson03 terraform apply -auto-approve
  - name: apply
    ansible.builtin.command: chdir=~/work/lesson03 terraform destroy -auto-approve
