apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-volume-data
spec:
  containers:
    - name: main-app
      image: nginx
      volumeMounts:
      - name:shared-data
        mountPath: /var/log/nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    - name: busybos-container
      image: busybox
        command:["sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep50; done"]
      volumeMounts:
      - name: shared-data
        mountPath: /var/log/nginx/
    volumes:
    - name: shared-data
    emptyDir: {}
