apiVersion: v1
kind: Pod
metadata:
  name: pgadmin
spec:
  containers:
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      valueFrom:
        secretKeyRef:
          name: pgadmin
          key: username
    - name: PGADMIN_DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgadmin
          key: password
